// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUYAtXCRcC9BhIKLnbyCAfZwWpCOvCrWE',
    appId: '1:447557130639:web:3ab9fad6e8d46ee50393fa',
    messagingSenderId: '447557130639',
    projectId: 'safe-chat-app-179f4',
    authDomain: 'safe-chat-app-179f4.firebaseapp.com',
    storageBucket: 'safe-chat-app-179f4.firebasestorage.app',
    measurementId: 'G-YG2SZ82V9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACgVWKBPLtFxDg47VHjrbetgHYaSiKf7o',
    appId: '1:447557130639:android:0fe58cf0ad13eb3c0393fa',
    messagingSenderId: '447557130639',
    projectId: 'safe-chat-app-179f4',
    storageBucket: 'safe-chat-app-179f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXJosmOwpPJW0KpYVhMMJCiZpIa7UQjy0',
    appId: '1:447557130639:ios:e06f5117546bb4920393fa',
    messagingSenderId: '447557130639',
    projectId: 'safe-chat-app-179f4',
    storageBucket: 'safe-chat-app-179f4.firebasestorage.app',
    iosBundleId: 'com.example.safeChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXJosmOwpPJW0KpYVhMMJCiZpIa7UQjy0',
    appId: '1:447557130639:ios:e06f5117546bb4920393fa',
    messagingSenderId: '447557130639',
    projectId: 'safe-chat-app-179f4',
    storageBucket: 'safe-chat-app-179f4.firebasestorage.app',
    iosBundleId: 'com.example.safeChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUYAtXCRcC9BhIKLnbyCAfZwWpCOvCrWE',
    appId: '1:447557130639:web:4dcbb6716275f5030393fa',
    messagingSenderId: '447557130639',
    projectId: 'safe-chat-app-179f4',
    authDomain: 'safe-chat-app-179f4.firebaseapp.com',
    storageBucket: 'safe-chat-app-179f4.firebasestorage.app',
    measurementId: 'G-DQKFKQZZN3',
  );
}
